### PR TITLE
fix($readme): add link to React Universal Component

### PR DESCRIPTION
**Pull request by faceyspacey**
I added a link to RUC in the readme.

Also, u now can represent multiple dynamically imported components with one `<UniversalComponent />`:

https://medium.com/faceyspacey/announcing-react-universal-component-2-0-babel-plugin-universal-import-5702d59ec1f4

So in your App.js file you have this:

```js
const App = () => (
  <div>
    <Helmet {...config.head} />
    <Hero />

    <Menu />
    <div className={style.container}>
      <Switch>
        <Route path="/" component={Home} exact />
        <Route path="/examples" component={Examples} exact />
        <RedirectWithStatus status={302} from="/home" to="/" />
        <Route path="/shell" component={Loading} exact />
        <Route component={NotFound} />
      </Switch>
    </div>
  </div>
)
```

You could do it like this:
```js
const UniversalComponent = universal(props => import(`../${props.page}`, {
  loading: Loading,
  error: NotFound
})

const App = () => (
  <div>
    <Helmet {...config.head} />
    <Hero />

    <Menu />
    <div className={style.container}>
       <Route path='/:page' render={({ match }) => <UniversalComponent page={match.params.page} />}
    </div>

      <Route path='/home' render={({ match }) => <Redirect to='/' />}
  </div>
)
```

This is a rough example, but obviously `params.page` needs the first letter capitalized, and the redirect implementation might need some work. But the point is you don't need 2 concepts: 
- Universal Component
- switch. 

Just Universal Component. And if the number of pages grows, you're already covered automatically by the *"dynamic expression"* passed to `import()`. 

Let me tell you guys a secret. Google React Router. The first React Router article from Medium is getting lots of traffic. I know because go to CodeSandBox. Then do a search. The sandbox from that article is directly ahead of mine at the top of the search results. There's no other reason than the placement in the search results. Search React React v4. It's #2 in google.

You guys should make an article with a better title (from an SEO standpoint):

`React Router v4 /w React Universal Component`
> notice your article starts with the exact keywords that are getting traffic

Then make sure to upgrade to the 2.0 style above. Explain how great it is, yada yada yada. Let me know if you need any help with it (maybe editing). It should be genuinely from you. But if you do this, I'll help you promote it. It will likely end up on this page 2. At least the results page with "v4" in the keywords. We may even be able to get help from the React Router people (i.e. some tweets). The reason is this:

https://reacttraining.com/react-router/web/guides/code-splitting
> check the bottom of the page

they have struggled with **simultaneous SSR + code splitting** for some time now. If they saw it down really nicely with React Router. Well, then they'd be inclined to tweet it, maybe even link it from their docs.

Lastly, u should also make a codesandbox (even tho that wont have SSR) so people can see it quickly in the browser.

### CODE REVIEW

**Comment by dawidvdh** [comment]
Hey @faceyspacey thanks for all of this going to start working through all of it now :)

**Comment by dawidvdh** [comment]
Hey @faceyspacey, Thanks again for all your input really appreciate the time you have put in, So I just want to firstly address upgrading to `2.0 style`.

After attempting to use the `2.0 style` I can see few benefits, I mean sure you get automated coverage with the "dynamic expression" passed to `import()`, however now your "pages" are routes and with the folder structure using the `component` and `container` paradigm `containers` are not necessarily pages but yet would be available to the router? 

I mean sure you obviously one wouldn't link what isn't a page but at the same time I would rather just not want it to have the ability to have access to containers that are not pages?

A Solution could be to create another folder "pages" that imports various containers and compiles pages out of them, but also now it feel like were adding a lot more boilerplate in order to use the dynamic expression and it would actually just be easier to add another `Route` to the `App`?

Secondly how would parameters work? I mean if we are going with this style:

```
<div className={style.container}>
	<Route path='/:page' render={({ match }) => <UniversalComponent page={match.params.page} />}
 </div>
```

then we lose the ability of specificing parameters in the documented way of:

```
<Route path="/user/:username" component={User}/>
```

and what happens when your home route is `/` it would then have to translate to `/home` in order to load up the Home page with the dynamic expression, I mean sure a `Redirect` could be put into place i guess?

I feel like this moving away from `react-router` and its documented behaviour which may make this all very difficult for people coming to this boilerplate and expecting `react-router` behaviour? 

I am still actively trying to make this work and finding ways around these problems however I feel like I am failing to see the real benefits of this for this exact use case?

Please let me know if I am being silly and not understanding what your trying to get across.

**Comment by faceyspacey** [comment]
The points you raised were what I was thinking as well, when it comes to React Router. That said, I think using React Router is architecturally a poor and naive approach to begin with. If you've studied my Redux-First Router articles, you know exactly what I think. 

> Basically the problems you described only exist because you have poor access to state in the view layer, as provided to you by shitty `<Route />` components. The full power of redux circumvents this and you have whatever path `param` or `page` variable in a consistent fashion wherever you need it. The routing happens all prior to redux state, and then derived potentially complex state lives in redux, which you can use professionally in the view layer.

That said it's about *business*, and React Router is popular. So I'd like to make *Universal* shine while using it. If dynamic expressions are not a good approach, that's not good for business, as that means *Universal* shines less.

But it's all good. I really gotta invest the time in RR myself. What was pasted above may not be *the* idiomatic solution, but I'm confident one exists that attains the best of both worlds. 

Regarding losing params here:
```js
<Route path="/user/:username" component={User}/>
```

I mean, you pass whatever you want to the component within the `render` prop function. So you can regain anything you need.

And as far as the `home` redirect, you don't need a redirect--you create a function that maps the page param or paths in general to their component name. It's like a 2 line function.

As far as the *"pages"* folder idea--exactly. That's what you do when you want to dynamically create chunks, or otherwise the webpack compiler ends up wasting time doing unnecessary work. 

Anyway, i'd close this (and hopefully merge the readme pr), as for now dynamic expressions probably dont make the most sense for your boilerplate. I personally dont like the idiom of passing a function to a route component's `render` prop. It looks bad, and aesthetics are important for adoption. At the end of the day, essentially React Router has its own mechanism for what dynamic expressions do: their `<Switch />` component. So perhaps the promoted RR usage is just like you have it with many dynamic imports based on *static expressions.*

Final thing: the `render` prop shouldnt actually be needed. This should do the job even better:

```js
const UniversalComponent = universal(import(props => `./pages/${props.match.params.page}`))
<Route path="/user/:page" component={UniversalComponent}/>
```

And sure u wanna convert it and handle `Home`:

```js
const findPage = props => capitalizeFirstLetter(props.match.params.page || 'home')
const UniversalComponent = universal(import(props => `./pages/${findPage(props)}`))

<Route path="/:page?" component={UniversalComponent}/>
```
> the question mark is the key ingredient that solves the problem you mentioned here. the param is now optional, and the `findPage` function knows how to do deal with it. Now we have one simple component to handle this stuff like a champ.

So bottom line is it works just fine--unless ur stuck on a "containers" folder paradigm. At the end of the day, that doesn't last beyond boilerplates. You need different folders to categorize different things. Creating a `pages` folder shouldn't be a worry, as it's a good thing: it differentiates "pages" from "widgets." I personally stopped using container folders long ago. I just prefer the container code in the component folder. I wanna to see it all together. Instead I have a selectors folder for advanced selectors so they dont clutter a component file. So the actual "container" code ends up being very little--just specifying keys a few times in mapStateToProps basically. 

So it's a good thing if you have a special designated folder for components that are already more "special" than the rest. But even if you really want them, the containers folder shouldn't be a problem--just nest it in `pages`, etc.

Final point: webpack will bundle all the files in the containers folder into their own chunks. If you don't mind the extra compilation time (which is fine in a boilerplate that will inevitably be re-arranged anyway), then the only thing your worried about is a user visiting /myWidget and then MyWidget getting its own page. Then just change `findPage` to be this:

```js
const pages = {
   foo: 'Foo',
   bar: 'Bar
}

const findPage = props => pages[props.match.params.page] || 'Home'
```

And that's the sorta stuff u do with Redux-First Router in general. Whether u do that in the reducer or a selector, or as an ad hoc function. The point is it's worthwhile flexibility in comparison to the limitations in React Router we just wrote all these paragraphs discussing. The above is fine code to write. There's zero wrong with it. It's only wrong in the eyes of those still hanging on to frameworks and the idea that a framework should do everything for you, and if you're not strictly using one of their idioms/tools and instead have to write custom code, ur doing it wrong. The new pro JS mindset is to be writing code like above all the time and rely on the least amount of packages. Push as much of your work into Redux, definitely dont use React Router :), and be a master of selectors. It's all about selectors at the end of the day. 

The challenge is simply the marketing angle when ur trying to make something approachable to new developers who are just trying to get React Router `<Route />` components to click with themselves. That's the real challenge. So the question is simply is this too much:

```js
const findPage = props => capitalizeFirstLetter(props.match.params.page || 'home')
const UniversalComponent = universal(import(props => `./pages/${findPage(props)}`))

<Route path="/:page?" component={UniversalComponent} />
```

I think it's just dandy--cuz u also have to keep in mind, ur targeting only users advanced enough to be trying to achieve simultaneous SSR + code splitting. U have to be at least a semi "power user" in the first place. 

As for not using the `render` prop--didnt we find a while back when we worked on ur thing that the problems were ultimately somewhere else (i think u werent passing the path to `createMemoryHistory`). There's no reason the above cant work. In fact, if we can get that to work, that's the Universal + RR vision nailed. 

A cherry on top would be if I added a function to react-universal-component where it transforms the props for you. So you could write it like this:


```js
const UniversalComponent = universal(import(page => `./pages/${page}`), {
   transformProps: props => capitalizeFirstLetter(props.match.params.page || 'home')
})

<Route path="/:page?" component={UniversalComponent} />
```

That basically solves things by having a built-in idiom for newer programmers that only feel comfortable when there are prescribed solutions.

Anyway, are u convinced, yes or no? It matters not what i think--as someone who barely uses RR who promotes an alternative approach. What is needed is something that appeals to the target RR audience, which u likely know better than me.

**Comment by rocbear** [comment]
@faceyspacey we'd like to try and keep compostability as an underlying principle to the boilerplate. While the redux based routing is something we'll explore, we want the reliance on any frameworks/libraries we use to be minimal.

Currently it's relatively easy to remove or replace `react-router` and `redux`, or more generally the routing and state management approaches we've chosen. Coupling those things together would make this slightly more complicated.

Similarly, the way you're suggesting we use `react-universal-component` feels like it's adding to coupling. I think being explicit in selectively including `universal` into our components and not introducing the concept of *pages* feels preferable.

These are more related to what we want the boilerplate to be, rather than how we feel about any specific technology.

I'll merge this change and create a branch for a `redux-first-router` version of the boilerplate so we can see how it feels and give people that option.

**Comment by faceyspacey** [comment]
all good. i figured as much. figured i'd just share my thoughts. thanks for the merge.

**Pull request merged**
